name: Deploy-uxpin

on: push

jobs:
  deploy-uxpin:
    name: UXpin update
    runs-on: ubuntu-latest
    if: "github.ref == 'refs/heads/master' && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@master
        with:
          ref: refs/heads/master
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.18.0"
      - name: Install
        run: yarn
      - name: Push To UXpin
        run: yarn push
        env:
          UXPIN_AUTH_TOKEN: 60fbad710b392f71cd9e68fbeb8f7fc932211d56
